sudo: required

language: java

services:
  - docker
  
branches:
  only:
    - master

install: true

script:
  - ./gradlew test -i
  - ./docker-build.sh $TRAVIS_COMMIT $TRAVIS_BUILD_NUMBER

deploy:
  - provider: script
    skip_cleanup: true
    script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin ; docker push sogis/ilivalidator-web-service-micronaut
    on:
      branch: master
